project_name: baf_complex
project_description: baf_complex
username: arendeiro
email: arendeiro@cemm.oeaw.ac.at

metadata:
  output_dir: /scratch/lab_bock/shared/projects/baf_complex
  results_subdir: data
  submission_subdir: submission
  pipeline_interfaces: /home/arendeiro/workspace/open_pipelines/pipeline_interface.yaml
  sample_annotation: /scratch/lab_bock/shared/projects/baf_complex/metadata/annotation.csv
  sample_subannotation: /scratch/lab_bock/shared/projects/baf_complex/metadata/merge_table.csv
  compare_table: /scratch/lab_bock/shared/projects/baf_complex/metadata/compare_table.csv

sample_attributes:
  - sample_name
  - cell_line
  - knockout
  - treatment
  - replicate
  - clone
  - batch
group_attributes:
  - knockout
  - treatment
  - replicate
  - clone
  - batch

data_sources:
  wgs: "/scratch/lab_bock/shared/projects/baf_complex/data/whole_genome/{sra_id}.bam"
  bsf: /scratch/lab_bsf/samples/{flowcell}/{flowcell}_{lane}_samples/{flowcell}_{lane}#{BSF_name}.bam

genomes:
  human: hg19
transcriptomes:
  human: hg19_cdna

compute:
  submission_template: templates/slurm_template.sub
  submission_command: sbatch

trackhubs:
  trackhub_dir: /data/groups/lab_bock/public_html/arendeiro/baf_complex/
  url: http://biomedical-sequencing.at/bocklab/arendeiro/baf_complex
